# Generated by Django 3.0.3 on 2020-02-18 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stuInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuNum', models.CharField(max_length=10)),
                ('stuName', models.CharField(max_length=30)),
                ('stuPassWord', models.CharField(max_length=16)),
                ('stuCollege', models.CharField(max_length=30)),
                ('stuImg', models.ImageField(default='userIcons/default_boy.png', upload_to='userIcons/')),
            ],
            options={
                'verbose_name': '用户信息',
            },
        ),
    ]
