# Generated by Django 3.0.3 on 2020-02-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stuinf',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterField(
            model_name='stuinf',
            name='stuImg',
            field=models.ImageField(default='icons/default_boy.png', upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='stuinf',
            name='stuNum',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
