# Generated by Django 2.2.5 on 2019-10-01 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='account',
        ),
        migrations.RemoveField(
            model_name='article',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Accout',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
