# Generated by Django 3.0.3 on 2020-02-25 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reading', '0003_article_as_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
    ]
